### ISSUE TITLE
Return to the Element List is broken

### ISSUE THREAD

**Issue by Raelsmyta** [abdullahalshubaia/Elemental#1]
Doesn't go back to the List.html

**Comment by abdullahalshubaia** [comment]
if you mean the  air.html page doesn't take you back to list.html
when clicking on "Return to the Elements List..."

this issue has been resolved.

user can click  on "Return to the Elements List..." 
and it should take the user to the element list page is expected.

**Comment by Raelsmyta** [comment]
The issue has been resolved. You can now click on "Return to the Element List" and it will bring you to the element list page.
