### ISSUE TITLE
Misspelling "Earth" word on Earth page

### ISSUE THREAD

**Issue by abdullahalshubaia** [abdullahalshubaia/Elemental#7]
Issue: on the list.html page when clicking on "Earth", there is a spelling mistake with the "Information on EATRH" instead of "EARTH" 

Expected Result: earth.html page shouldn't include any spelling error.

**Comment by Raelsmyta** [comment]
Issue has been fixed. The correct spelling of earth is now implemented. Note that we were supposed to check each others bugs and close them. However, I have checked all of your bugs and they have been corrected.

**Comment by abdullahalshubaia** [comment]
verified
