### ISSUE TITLE
On Water page it says "Information on AIR"

### ISSUE THREAD

**Issue by abdullahalshubaia** [abdullahalshubaia/Elemental#8]
Issue: Water page has false information. 
it says "Information on AIR"

Expected results: in the list.html when clicking on "Water"  it should show  "Information on WATER" on the water.html page.

**Comment by Raelsmyta** [comment]
Issue has been fixed. Information of AIR has been changed to Information of EARTH. Note that we were supposed to check each others bugs and close them. However, I have checked all of your bugs and they have been corrected.

**Comment by abdullahalshubaia** [comment]
verified

and i have reopen the issue so u can verify and close it.
